name: Python Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write  # Necesario para GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: üîê Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: üèóÔ∏è Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/dkcatotin/jeremy-catota:latest

    - name: üîå Prueba de conexi√≥n SSH con el servidor
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_SSH_PORT }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          echo "Conexi√≥n exitosa desde GitHub Actions"
          pwd
          date
          whoami
          hostname
          uptime

    - name: üì¶ Pasar stack.yml al servidor 
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_SSH_PORT }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/automatizar"

    - name: üöÄ Deploy en el servidor con Docker Swarm
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_SSH_PORT }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          echo "Realizando deploy a Docker Swarm"
          cd ~/automatizar

          # Login GHCR
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u dkcatotin --password-stdin

          # Pull de imagen
          docker pull ghcr.io/dkcatotin/jeremy-catota:latest

          # Borrar el stack quintob
          docker stack rm quintob || true

          # Esperar que los servicios se detengan
          sleep 40

          # Deploy limpio
          docker stack deploy --with-registry-auth -c stack.yml quintob

          # Esperar inicio del stack
          sleep 30

          # Ver contenedores activos
          docker ps
